from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from datetime import datetime

styles = getSampleStyleSheet()

title_style = styles["Title"]
title_style.alignment = TA_CENTER

heading_style = styles["Heading2"]

normal_style = styles["BodyText"]


def generate_pdf(
    filename,
    candidate,
    match,
    ats,
    recommendation,
    matched,
    missing,
    ai_review
):

    doc = SimpleDocTemplate(filename)

    story = []

    # -----------------------------
    # Header
    # -----------------------------
    story.append(Paragraph("VELTRIX AI", title_style))
    story.append(
        Paragraph(
            "AI-Powered Recruitment Intelligence Platform",
            styles["Heading3"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Report Generated:</b> {datetime.now().strftime('%d %B %Y')}",
            normal_style
        )
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Candidate Details
    # -----------------------------
    story.append(
        Paragraph("Candidate Information", heading_style)
    )

    story.append(
        Paragraph(f"<b>Candidate Name:</b> {candidate}", normal_style)
    )

    story.append(
        Paragraph(f"<b>Resume Match:</b> {match}%", normal_style)
    )

    story.append(
        Paragraph(f"<b>ATS Score:</b> {ats}/100", normal_style)
    )

    story.append(
        Paragraph(f"<b>Recommendation:</b> {recommendation}", normal_style)
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Matched Skills
    # -----------------------------
    story.append(
        Paragraph("Matched Skills", heading_style)
    )

    if matched:
        for skill in matched:
            story.append(
                Paragraph(f"• {skill}", normal_style)
            )
    else:
        story.append(
            Paragraph("No matched skills found.", normal_style)
        )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Missing Skills
    # -----------------------------
    story.append(
        Paragraph("Missing Skills", heading_style)
    )

    if missing:
        for skill in missing:
            story.append(
                Paragraph(f"• {skill}", normal_style)
            )
    else:
        story.append(
            Paragraph("No missing skills.", normal_style)
        )

    story.append(Spacer(1, 20))

    # -----------------------------
    # AI Review
    # -----------------------------
    story.append(
        Paragraph("AI Resume Review", heading_style)
    )

    story.append(
        Paragraph(
            ai_review.replace("\n", "<br/>"),
            normal_style
        )
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Footer
    # -----------------------------
    story.append(
        Paragraph(
            "<b>Generated by Veltrix AI</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)